version: "3.8"

services:
  client:
    image: node:21.0.0-alpine
    user: node
    working_dir: /home/node
    command: sh -c "npm install && npm run start"
    ports:
      - "5173:5173"
    volumes:
      - ./client:/home/node

  server:
    image: node:21.0.0-alpine
    user: node
    tty: true
    stdin_open: true
    working_dir: /home/node
    entrypoint: sh -c
    command: sh -c "chmod +x /init.sh && /init.sh"
    ports:
      - 8000:8000
    volumes:
      - ./server:/home/node
      - ./backend.sh:/init.sh
    environment:
      - HOST=0.0.0.0
      - MONGO_URL=mongodb://root:password@mongodb:27017/app?authSource=admin
    depends_on:
      - db
      - mongodb

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: alikhelifa147
      MYSQL_DATABASE: ecommercedb
      MYSQL_USER: me
      MYSQL_PASSWORD: ali123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --pid-file=/var/lib/mysql/mysql.pid

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: alikhelifa147

  mongodb:
    image: mongo
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db-data:/data/db
      - ./mongo/data:/home/data
    working_dir: /home/data
    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - client
      - server
volumes:
  mysql-data: {}
  db-data: {}
