version: "3.8"

services:
  client:
    image: node:21.0.0-alpine
    user: node
    working_dir: /home/node
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - ./client:/home/node

  server:
    image: node:21.0.0-alpine
    user: node
    tty: true
    stdin_open: true
    working_dir: /home/node
    entrypoint: sh -c
    command: '"npm install && npm run dev"'
    ports:
      - 8000:8000
    volumes:
      - ./server:/home/node
    environment:
      - HOST=0.0.0.0

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: alikhelifa147
      MYSQL_DATABASE: ecommercedb
      MYSQL_USER: me
      MYSQL_PASSWORD: ali123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --pid-file=/var/lib/mysql/mysql.pid

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: alikhelifa147

volumes:
  mysql-data:
